from typing import Dict, Any, Protocol


class Connector(Protocol):
    """Interface for all integration connectors."""
    
    @property
    def id(self) -> str: ...
    
    @property
    def name(self) -> str: ...
    
    def connect(self) -> bool: ...
    
    def authenticate(self, credentials: Dict[str, str]) -> bool: ...
    
    def send(self, endpoint: str, payload: Dict[str, Any]) -> Dict[str, Any]: ...
    
    def receive(self, endpoint: str, params: Dict[str, Any] = None) -> Dict[str, Any]: ...
    
    def health_check(self) -> bool: ...
