"""Initial enterprise schema

Revision ID: f698e30e0622
Revises: 
Create Date: 2026-07-07 16:36:41.236269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f698e30e0622'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_region',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('claim_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('claim_type_id', sa.UUID(), nullable=False),
    sa.Column('date_of_loss', sa.Date(), nullable=False),
    sa.Column('date_received', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('composite_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('stp_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref')
    )
    op.create_table('claim_party',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('claim_type',
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_ar', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('damage_severity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('damage_zone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('discrepancy_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('document_type',
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_ar', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('event_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('extraction_method',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('flag_reason',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('injury_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('insurance_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=64), nullable=False),
    sa.Column('insurer_id', sa.UUID(), nullable=False),
    sa.Column('product_type_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('policyholder_party_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','EXPIRED','CANCELLED','SUSPENDED')", name='chk_policy_status'),
    sa.CheckConstraint('expiry_date > effective_date', name='chk_policy_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_table('insurer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('operator_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('party_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_type',
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_ar', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('prognosis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('road_condition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('weather_condition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('claim_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('classification_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('page_range_start', sa.Integer(), nullable=False),
    sa.Column('page_range_end', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('classification_confidence BETWEEN 0 AND 1', name='chk_doc_confidence'),
    sa.CheckConstraint('duplicate_of_id IS DISTINCT FROM id', name='chk_dup_self'),
    sa.CheckConstraint('page_range_end >= 1', name='chk_page_end'),
    sa.CheckConstraint('page_range_end >= page_range_start', name='chk_page_range'),
    sa.CheckConstraint('page_range_start >= 1', name='chk_page_start'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['claim_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('entity_table', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("actor_type IN ('SYSTEM','AI_AGENT','HUMAN_OPERATOR')", name='chk_event_actor_type'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_vehicle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('is_insured_vehicle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['claim_party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['operator_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('claim_discrepancy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('discrepancy_type_id', sa.UUID(), nullable=False),
    sa.Column('entity_a_table', sa.String(length=64), nullable=False),
    sa.Column('entity_a_id', sa.UUID(), nullable=False),
    sa.Column('entity_a_field', sa.String(length=64), nullable=False),
    sa.Column('entity_b_table', sa.String(length=64), nullable=False),
    sa.Column('entity_b_id', sa.UUID(), nullable=False),
    sa.Column('entity_b_field', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("severity IN ('INFO','WARNING','CRITICAL')", name='chk_disc_severity'),
    sa.ForeignKeyConstraint(['discrepancy_type_id'], ['discrepancy_type.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_page',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('original_page_number', sa.Integer(), nullable=False),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('ocr_hocr_uri', sa.Text(), nullable=False),
    sa.Column('orientation_corrected_deg', sa.Integer(), nullable=True),
    sa.Column('resolution_dpi', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_missing_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('original_page_number >= 1', name='chk_orig_page_number'),
    sa.CheckConstraint('page_number >= 1', name='chk_page_number'),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 1', name='chk_quality_score'),
    sa.ForeignKeyConstraint(['document_id'], ['claim_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_doc_page')
    )
    op.create_table('medical_certificate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['claim_document.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['claim_party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('national_id', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('address_line_1', sa.String(length=256), nullable=True),
    sa.Column('address_city', sa.String(length=128), nullable=True),
    sa.Column('address_postal_code', sa.String(length=16), nullable=True),
    sa.Column('address_country_iso', sa.String(length=2), nullable=True),
    sa.Column('driving_license_number', sa.String(length=32), nullable=True),
    sa.Column('driving_license_category', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("origin IN ('AI_EXTRACTION','HUMAN_CORRECTION','DB_ENRICHMENT')", name='chk_party_origin'),
    sa.CheckConstraint('version >= 1', name='chk_party_version'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['claim_party.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'version', name='uq_party_version')
    )
    op.create_table('police_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['claim_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('composite_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("decided_by IN ('AI_ENGINE','HUMAN_OPERATOR')", name='chk_vd_decided_by'),
    sa.CheckConstraint("decision IN ('STP_APPROVED','HITL_REVIEW','REJECTED','PENDING_DOCUMENTS')", name='chk_vd_decision'),
    sa.CheckConstraint('composite_confidence BETWEEN 0 AND 1', name='chk_vd_confidence'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_damage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('damage_zone_id', sa.UUID(), nullable=False),
    sa.Column('severity_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['damage_zone_id'], ['damage_zone.id'], ),
    sa.ForeignKeyConstraint(['severity_id'], ['damage_severity.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['claim_vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('registration_plate', sa.String(length=20), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('fuel_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("fuel_type IN ('GASOLINE','DIESEL','ELECTRIC','HYBRID','LPG','UNKNOWN') OR fuel_type IS NULL", name='chk_fuel_type'),
    sa.CheckConstraint("origin IN ('AI_EXTRACTION','HUMAN_CORRECTION','DB_ENRICHMENT')", name='chk_vehicle_origin'),
    sa.CheckConstraint('version >= 1', name='chk_vehicle_version'),
    sa.CheckConstraint('year BETWEEN 1900 AND 2100 OR year IS NULL', name='chk_year'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['claim_vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'version', name='uq_vehicle_version')
    )
    op.create_table('field_provenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_table', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source_page_id', sa.UUID(), nullable=True),
    sa.Column('bbox_x1', sa.Integer(), nullable=True),
    sa.Column('bbox_y1', sa.Integer(), nullable=True),
    sa.Column('bbox_x2', sa.Integer(), nullable=True),
    sa.Column('bbox_y2', sa.Integer(), nullable=True),
    sa.Column('extraction_method_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('raw_ocr_token', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('(bbox_x1 IS NULL AND bbox_y1 IS NULL AND bbox_x2 IS NULL AND bbox_y2 IS NULL) OR (bbox_x1 IS NOT NULL AND bbox_y1 IS NOT NULL AND bbox_x2 IS NOT NULL AND bbox_y2 IS NOT NULL)', name='chk_bbox_complete'),
    sa.CheckConstraint('bbox_x1 IS NULL OR (bbox_x2 > bbox_x1 AND bbox_y2 > bbox_y1)', name='chk_bbox_valid'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='chk_prov_confidence'),
    sa.ForeignKeyConstraint(['extraction_method_id'], ['extraction_method.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_table', 'entity_id', 'field_name', name='uq_provenance')
    )
    op.create_table('medical_cert_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('issuing_facility', sa.String(length=256), nullable=True),
    sa.Column('issuing_doctor', sa.String(length=256), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('initial_disability_days', sa.Integer(), nullable=True),
    sa.Column('hospitalization_days', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("origin IN ('AI_EXTRACTION','HUMAN_CORRECTION','DB_ENRICHMENT')", name='chk_medcert_origin'),
    sa.CheckConstraint('hospitalization_days >= 0 OR hospitalization_days IS NULL', name='chk_hosp_days'),
    sa.CheckConstraint('initial_disability_days >= 0 OR initial_disability_days IS NULL', name='chk_disability_days'),
    sa.CheckConstraint('version >= 1', name='chk_medcert_version'),
    sa.ForeignKeyConstraint(['certificate_id'], ['medical_certificate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id', 'version', name='uq_medcert_version')
    )
    op.create_table('medical_finding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('icd10_code', sa.String(length=8), nullable=True),
    sa.Column('body_region_id', sa.UUID(), nullable=True),
    sa.Column('injury_type_id', sa.UUID(), nullable=True),
    sa.Column('prognosis_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['body_region_id'], ['body_region.id'], ),
    sa.ForeignKeyConstraint(['certificate_id'], ['medical_certificate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['injury_type_id'], ['injury_type.id'], ),
    sa.ForeignKeyConstraint(['prognosis_id'], ['prognosis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('police_party_statement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('statement_summary', sa.Text(), nullable=True),
    sa.Column('is_consistent_with_facts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['claim_party.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['police_report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('police_report_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('report_number', sa.String(length=64), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('station_name', sa.String(length=256), nullable=True),
    sa.Column('accident_location', sa.String(length=512), nullable=True),
    sa.Column('accident_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weather_condition_id', sa.UUID(), nullable=True),
    sa.Column('road_condition_id', sa.UUID(), nullable=True),
    sa.Column('liability_split_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alcohol_test_result', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("alcohol_test_result IN ('POSITIVE','NEGATIVE','NOT_TESTED') OR alcohol_test_result IS NULL", name='chk_alcohol_test'),
    sa.CheckConstraint("origin IN ('AI_EXTRACTION','HUMAN_CORRECTION','DB_ENRICHMENT')", name='chk_pr_origin'),
    sa.CheckConstraint('version >= 1', name='chk_pr_version'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['police_report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['road_condition_id'], ['road_condition.id'], ),
    sa.ForeignKeyConstraint(['weather_condition_id'], ['weather_condition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version', name='uq_pr_version')
    )
    op.create_table('validation_field_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('entity_table', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('flag_reason_id', sa.UUID(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['validation_decision.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_reason_id'], ['flag_reason.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key('fk_claim_file_policy_id', 'claim_file', 'insurance_policy', ['policy_id'], ['id'])
    op.create_foreign_key('fk_claim_file_claim_type_id', 'claim_file', 'claim_type', ['claim_type_id'], ['id'])
    op.create_foreign_key('fk_claim_file_status_id', 'claim_file', 'claim_status', ['status_id'], ['id'])
    
    op.create_foreign_key('fk_claim_party_claim_id', 'claim_party', 'claim_file', ['claim_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_claim_party_role_id', 'claim_party', 'party_role', ['role_id'], ['id'])
    
    op.create_foreign_key('fk_insurance_policy_insurer_id', 'insurance_policy', 'insurer', ['insurer_id'], ['id'])
    op.create_foreign_key('fk_insurance_policy_policyholder_party_id', 'insurance_policy', 'claim_party', ['policyholder_party_id'], ['id'])
    op.create_foreign_key('fk_insurance_policy_product_type_id', 'insurance_policy', 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_field_flag')
    op.drop_table('police_report_version')
    op.drop_table('police_party_statement')
    op.drop_table('medical_finding')
    op.drop_table('medical_cert_version')
    op.drop_table('field_provenance')
    op.drop_table('vehicle_version')
    op.drop_table('vehicle_damage')
    op.drop_table('validation_decision')
    op.drop_table('police_report')
    op.drop_table('party_version')
    op.drop_table('medical_certificate')
    op.drop_table('document_page')
    op.drop_table('claim_discrepancy')
    op.drop_table('operator')
    op.drop_table('claim_vehicle')
    op.drop_table('claim_event')
    op.drop_table('claim_document')
    op.drop_table('weather_condition')
    op.drop_table('road_condition')
    op.drop_table('prognosis')
    op.drop_table('product_type')
    op.drop_table('party_role')
    op.drop_table('operator_role')
    op.drop_table('insurer')
    op.drop_table('insurance_policy')
    op.drop_table('injury_type')
    op.drop_table('flag_reason')
    op.drop_table('extraction_method')
    op.drop_table('event_type')
    op.drop_table('document_type')
    op.drop_table('discrepancy_type')
    op.drop_table('damage_zone')
    op.drop_table('damage_severity')
    op.drop_table('claim_type')
    op.drop_table('claim_status')
    op.drop_table('claim_party')
    op.drop_table('claim_file')
    op.drop_table('body_region')
    # ### end Alembic commands ###
